"""Kubernetes manifest generator for UHCR workloads."""

import os
import sys

from uhcr.containerization.config import K8sConfig


class KubernetesGenerator:
    """Generates Kubernetes deployment manifests for UHCR workloads."""

    def __init__(self, config: K8sConfig):
        """Initialize the generator with a K8sConfig.

        Args:
            config: Kubernetes configuration specifying script path, image name,
                    namespace, replicas, and resource requests/limits.
        """
        self.config = config

    def generate(self) -> str:
        """Returns the deployment.yaml content as a string.

        Generates a Kubernetes Deployment manifest with namespace, replicas,
        container image, and optional resource requests/limits. When resource
        values are None, the resources section is omitted entirely.

        Returns:
            The generated deployment.yaml content.
        """
        script_name = os.path.splitext(os.path.basename(self.config.script_path))[0]
        app_name = self.config.image_name.split(":")[0]  # strip tag for labels

        lines = [
            "# Generated by UHCR CLI",
            "apiVersion: apps/v1",
            "kind: Deployment",
            "metadata:",
            f"  name: {app_name}",
            f"  namespace: {self.config.namespace}",
            "spec:",
            f"  replicas: {self.config.replicas}",
            "  selector:",
            "    matchLabels:",
            f"      app: {app_name}",
            "  template:",
            "    metadata:",
            "      labels:",
            f"        app: {app_name}",
            "    spec:",
            "      containers:",
            f"        - name: {app_name}",
            f"          image: {self.config.image_name}",
        ]

        # Add resource requests/limits if available
        if self._has_resources():
            lines.append("          resources:")
            if self.config.cpu_request or self.config.memory_request:
                lines.append("            requests:")
                if self.config.cpu_request:
                    lines.append(f'              cpu: "{self.config.cpu_request}"')
                if self.config.memory_request:
                    lines.append(f'              memory: "{self.config.memory_request}"')
            if self.config.cpu_limit or self.config.memory_limit:
                lines.append("            limits:")
                if self.config.cpu_limit:
                    lines.append(f'              cpu: "{self.config.cpu_limit}"')
                if self.config.memory_limit:
                    lines.append(f'              memory: "{self.config.memory_limit}"')

        lines.append("")  # trailing newline
        return "\n".join(lines)

    def _has_resources(self) -> bool:
        """Check if any resource requests or limits are configured."""
        return any([
            self.config.cpu_request,
            self.config.cpu_limit,
            self.config.memory_request,
            self.config.memory_limit,
        ])

    def write(self, output_dir: str) -> str:
        """Writes deployment.yaml to output_dir and returns the absolute path.

        Checks if the directory is writable, warns on stderr if overwriting
        an existing deployment.yaml, writes the file, and prints the path
        to stdout.

        Args:
            output_dir: Directory where deployment.yaml will be written.

        Returns:
            The absolute path to the written deployment.yaml.

        Raises:
            PermissionError: If the output directory is not writable.
        """
        output_dir = os.path.abspath(output_dir)
        manifest_path = os.path.join(output_dir, "deployment.yaml")

        # Check if directory is writable
        if not os.access(output_dir, os.W_OK):
            msg = f"Error: Directory is not writable: {output_dir}"
            print(msg, file=sys.stderr)
            raise PermissionError(msg)

        # Check if deployment.yaml already exists and warn
        if os.path.exists(manifest_path):
            print(
                "Warning: Overwriting existing deployment.yaml",
                file=sys.stderr,
            )

        # Generate and write the manifest
        content = self.generate()
        with open(manifest_path, "w", encoding="utf-8") as f:
            f.write(content)

        # Print path to stdout on success
        print(manifest_path)

        return manifest_path
