"""Dockerfile generator for UHCR workloads."""

import os
import sys

from uhcr.containerization.config import DockerConfig


class DockerGenerator:
    """Generates Dockerfiles for UHCR workloads."""

    def __init__(self, config: DockerConfig):
        """Initialize the generator with a DockerConfig.

        Args:
            config: Docker configuration specifying script path, image name,
                    base image, and compilation mode.
        """
        self.config = config

    def generate(self) -> str:
        """Returns the Dockerfile content as a string.

        Generates a Dockerfile with FROM, WORKDIR, RUN pip install,
        COPY, and ENTRYPOINT directives. In compiled mode, copies
        compiled artifacts instead of the source script.

        Returns:
            The generated Dockerfile content.
        """
        script_name = os.path.basename(self.config.script_path)
        base_image = self.config.base_image

        lines = [
            "# Generated by UHCR CLI",
            f"FROM {base_image}",
            "",
            "WORKDIR /app",
            "",
            "RUN pip install --no-cache-dir uhcr",
            "",
        ]

        if self.config.is_compiled:
            # In compiled mode, copy the compiled artifacts directory
            compiled_name = os.path.splitext(script_name)[0] + ".uhcrc"
            lines.append(f"COPY {compiled_name} .")
            lines.append("")
            lines.append(f'ENTRYPOINT ["python", "-m", "uhcr.cli", "run", "{compiled_name}"]')
        else:
            lines.append(f"COPY {script_name} .")
            lines.append("")
            lines.append(f'ENTRYPOINT ["python", "-m", "uhcr.cli", "run", "{script_name}"]')

        lines.append("")  # trailing newline
        return "\n".join(lines)

    def write(self, output_dir: str) -> str:
        """Writes the Dockerfile to output_dir and returns the absolute path.

        Checks if the directory is writable, warns on stderr if overwriting
        an existing Dockerfile, writes the file, and prints the path to stdout.

        Args:
            output_dir: Directory where the Dockerfile will be written.

        Returns:
            The absolute path to the written Dockerfile.

        Raises:
            PermissionError: If the output directory is not writable.
        """
        output_dir = os.path.abspath(output_dir)
        dockerfile_path = os.path.join(output_dir, "Dockerfile")

        # Check if directory is writable
        if not os.access(output_dir, os.W_OK):
            msg = f"Error: Directory is not writable: {output_dir}"
            print(msg, file=sys.stderr)
            raise PermissionError(msg)

        # Check if Dockerfile already exists and warn
        if os.path.exists(dockerfile_path):
            print(
                "Warning: Overwriting existing Dockerfile",
                file=sys.stderr,
            )

        # Generate and write the Dockerfile
        content = self.generate()
        with open(dockerfile_path, "w", encoding="utf-8") as f:
            f.write(content)

        # Print path to stdout on success
        print(dockerfile_path)

        return dockerfile_path
