"""Cross-compilation support: emit ARM64 machine code bytes on any host architecture.

This module allows x86_64 (or any non-ARM64) hosts to compile UHCR IR functions
to AArch64 machine code without executing the generated bytes.  The output is
suitable for writing to a file, embedding in a firmware image, or transferring
to an ARM64 device for execution.

Example::

    from uhcr.compiler.ir import Function, Type
    from uhcr.compiler.aarch64.cross_compile import CrossCompiler, cross_compile
    from uhcr.compiler.aarch64.target_profile import TargetProfile

    # Build an IR function (omitted for brevity)
    func: Function = ...

    # Option 1 — module-level helper
    arm64_bytes = cross_compile(func)

    # Option 2 — explicit compiler instance
    compiler = CrossCompiler(TargetProfile.mobile_iot())
    arm64_bytes = compiler.compile(func)
    compiler.compile_to_file(func, "/tmp/kernel.bin")
"""

from __future__ import annotations

import logging
import platform
from pathlib import Path
from typing import Optional

from uhcr.compiler.ir import Function
from uhcr.compiler.aarch64.codegen import AArch64CodeGenerator
from uhcr.compiler.aarch64.target_profile import TargetProfile

_log = logging.getLogger(__name__)


def _host_is_aarch64() -> bool:
    """Return ``True`` when the current process is running on an ARM64 host."""
    machine = platform.machine().lower()
    return machine in ("arm64", "aarch64")


class CrossCompiler:
    """Wraps :class:`~uhcr.compiler.aarch64.codegen.AArch64CodeGenerator` for
    safe cross-compilation from any host architecture to ARM64.

    The compiler emits raw AArch64 machine-code bytes but **never executes**
    them, making it safe to use on x86_64 hosts where the generated code would
    be invalid native instructions.

    Args:
        target_profile: Describes the ARM64 target device capabilities and
            constraints (ISA baseline, NEON features, Apple Silicon, etc.).
            Defaults to :meth:`~TargetProfile.default` when not supplied.

    Example::

        compiler = CrossCompiler(TargetProfile.mobile_iot())
        arm64_bytes = compiler.compile(my_func)
    """

    def __init__(self, target_profile: TargetProfile) -> None:
        self._profile = target_profile
        if self.is_cross_compiling():
            _log.debug(
                "CrossCompiler: cross-compiling to ARM64 from %s host",
                platform.machine(),
            )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def compile(self, func: Function) -> bytes:
        """Compile an IR function to ARM64 machine-code bytes.

        The bytes are **not** executed — they are safe to produce on any host
        architecture.  The caller is responsible for writing them to a file or
        transferring them to an ARM64 device.

        Args:
            func: The UHCR IR :class:`~uhcr.compiler.ir.Function` to compile.

        Returns:
            Raw AArch64 machine-code bytes for *func*.

        Raises:
            ValueError: If *func* has no basic blocks (empty function body).
        """
        if not func.blocks:
            raise ValueError(
                f"Cannot compile function '{func.name}': function has no basic blocks."
            )

        codegen = AArch64CodeGenerator(func)
        machine_code: bytes = codegen.compile()
        _log.debug(
            "CrossCompiler: compiled '%s' → %d bytes (ARM64)",
            func.name,
            len(machine_code),
        )
        return machine_code

    def compile_to_file(self, func: Function, output_path: str) -> None:
        """Compile an IR function and write the raw ARM64 bytes to a file.

        The output file contains only the raw machine-code bytes with no ELF
        or Mach-O wrapper.  Existing files at *output_path* are overwritten.

        Args:
            func: The UHCR IR :class:`~uhcr.compiler.ir.Function` to compile.
            output_path: Filesystem path where the raw bytes will be written.

        Raises:
            ValueError: If *func* has no basic blocks.
            OSError: If the output file cannot be written.
        """
        machine_code = self.compile(func)
        path = Path(output_path)
        path.write_bytes(machine_code)
        _log.debug(
            "CrossCompiler: wrote %d bytes to '%s'",
            len(machine_code),
            output_path,
        )

    def is_cross_compiling(self) -> bool:
        """Return ``True`` when the current host is **not** an ARM64 machine.

        When this returns ``True`` the generated bytes cannot be executed
        natively on the host and must be transferred to an ARM64 device.

        Returns:
            ``True`` on x86_64 (or any non-ARM64) hosts, ``False`` on ARM64.
        """
        return not _host_is_aarch64()

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    @property
    def target_profile(self) -> TargetProfile:
        """The :class:`~TargetProfile` this compiler targets."""
        return self._profile


# ---------------------------------------------------------------------------
# Module-level convenience function
# ---------------------------------------------------------------------------


def cross_compile(
    func: Function,
    target_profile: Optional[TargetProfile] = None,
) -> bytes:
    """Compile an IR function to ARM64 machine-code bytes.

    Convenience wrapper that creates a :class:`CrossCompiler` with the given
    *target_profile* (or :meth:`~TargetProfile.default` when ``None``) and
    returns the compiled bytes without executing them.

    Args:
        func: The UHCR IR :class:`~uhcr.compiler.ir.Function` to compile.
        target_profile: Optional ARM64 target profile.  When ``None``, the
            :meth:`~TargetProfile.default` profile is used.

    Returns:
        Raw AArch64 machine-code bytes for *func*.

    Example::

        arm64_bytes = cross_compile(my_func)
        arm64_bytes = cross_compile(my_func, TargetProfile.mobile_iot())
    """
    if target_profile is None:
        target_profile = TargetProfile.default()
    compiler = CrossCompiler(target_profile)
    return compiler.compile(func)
