name: Deploy Website

on:
  push:
    branches:
      - uhcr-v1

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Install Dependencies
        working-directory: ./web
        run: npm ci

      - name: Build Website
        working-directory: ./web
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./web/dist

  deploy:

    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages

    permissions:
      pages: write
      id-token: write

    steps:

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4