name: Test

on:
  push:
    branches:
      - uhcr-v2

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Verify Files
        run: |
          pwd
          ls
          ls web

      - name: Install Dependencies
        working-directory: ./web
        run: npm ci

      - name: Build
        working-directory: ./web
        run: npm run build

      - name: Lint
        working-directory: ./web
        run: npm run lint