name: Test

on:
  push:
    branches:
      - uhcr-v1

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Install Dependencies
        working-directory: ./web
        run: npm ci

      - name: Build Project
        working-directory: ./web
        run: npm run build

      - name: Run Linter
        working-directory: ./web
        run: npm run lint